name: "GPT Localize Action"
description: "Easily keep your translation files up-to-date and in sync with the latest English source strings using GPT-4."
author: "Vivek Maskara"
branding:
  color: "blue"
  icon: "globe"

inputs:
  openai_api_key:
    description: "OpenAI API key for fetching translations"
    required: true
  personal_access_token:
    description: "Personal Access Token to create branches and PRs"
    required: true
  locales_path:
    description: "The path to the locales directory relative to the repository root"
    required: true
    default: ""
  base_language:
    description: "The base language for translations (default: en)"
    required: false
    default: "en"
  base_file:
    description: "The base translation file (default: en.json)"
    required: false
    default: "en.json"

outputs:
  has_changes:
    description: "Indicates if any translation changes were made"
    value: ${{ steps.check_changes.outputs.has_changes }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Checkout action repository
      uses: actions/checkout@v3
      with:
        repository: mangoappstudio/gpt-localize-action
        path: action-repo
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Install dependencies
      shell: bash
      working-directory: ./action-repo/scripts/translate
      run: yarn install

    - name: Run translation update script
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: |
        node action-repo/scripts/translate/index.js -d ${{ inputs.locales_path }} -s ${{ inputs.base_language }} -f ${{ inputs.base_file }}
        # Clean up action-repo after running script
        rm -rf action-repo

    - name: Check for changes
      id: check_changes
      shell: bash
      run: |
        if git status --porcelain "${{ inputs.locales_path }}" | grep .; then
          echo "Changes detected"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create pull request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.personal_access_token }}
        commit-message: "Update translations [ci skip]"
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        branch: update-translations
        branch-suffix: timestamp
        delete-branch: true
        base: main
        title: "Update Translations"
        body: |
          This PR includes updated translations based on the latest changes to '${{ inputs.base_file }}'.
          
          - Auto-generated by [GPT Localize Action](https://github.com/mangoappstudio/gpt-localize-action)
        labels: |
          translations
          automated pr
        draft: false
